services:
  fixed-leader-optimizer:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runFixedLeaderOptimizer

  cutting-classic-vmc-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runCuttingClassicVMCBatch

  cutting-field-vmc-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runCuttingFixedLeaderBatch

  self-integration-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runSelfIntegrationBatch

  self-repair-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runSelfRepairBatch

  self-optimization-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/simulationLauncher/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runSelfOptimizationBatch

volumes:
  angela.cortecchia-volume:
    external: true