services:
  fixed-leader-optimizer:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runFixedLeaderOptimizer

volumes:
  angela.cortecchia-volume:
    external: true