services:
  prepare:
    image: alpine:3.21.0
    volumes:
      - .:/experiment:rw
    entrypoint: /bin/sh -c
    command:
      - |
        mkdir -p /experiment/data
        chmod 777 /experiment/data
        mkdir -p /experiment/charts
        chmod 777 /experiment/charts

  fieldVMC-fixed-leader-simulation:
    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderFieldVMC/Dockerfile
    environment:
      CLONING_RANGE: 5
      DEFAULT: 0
      LEADER_RADIUS: 100.0
      MAX: 20
      MAX_CHILDREN: 3
      MAX_RESOURCE: 1000.0
      MIN: 0
      MIN_SPAWN_WAIT: 40.0
      RESOURCE_LOWER_BOUND: 1.0
    depends_on:
      - prepare
    volumes:
      - ./data:/experiment/data
      
  classic-vmc-simulation:
    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/classicVMC/Dockerfile
    environment:
      CLONING_RANGE: 5
      CONST_COMPETITION_RATE: 2
      CONST_CONSUMPTION_RATE: 0.1
      CONST_PRODUCTION_RATE: 0.1
      CONST_TRANSFER_RATE: 0.5
      DEFAULT: 0
      MAX: 20
      MAX_CHILDREN: 3
      MAX_RESOURCE: 3.0
      MAX_SUCCESS: 500.0
      MIN: 0
      MIN_SPAWN_WAIT: 21
      RESOURCE_LOWER_BOUND: 5.0
      SENSOR_COMPETITION_RATE: 0.1
      SENSOR_PRODUCTION_RATE: 1.0
      SENSOR_TRANSFER_RATE: 0.5
      VESSELS_ADAPTATION_RATE: 0.9
    depends_on:
      - prepare
    volumes:
      - ./data:/experiment/data
#
#  simulation2:
#    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
#    build:
#      context: .
#      dockerfile: ./docker/sim/Dockerfile
#    environment:
#      MIN: 6
#      MAX: 10
#      DEFAULT: 7
#    depends_on:
#      - prepare
#    volumes:
#      - ./data:/experiment/data
#
#  simulation3:
#    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
#    build:
#      context: .
#      dockerfile: ./docker/sim/Dockerfile
#    environment:
#      MIN: 11
#      MAX: 15
#      DEFAULT: 12
#    depends_on:
#      - prepare
#    volumes:
#      - ./data:/experiment/data

  charts:
    depends_on:
      prepare:
        condition: service_completed_successfully
      fieldVMC-fixed-leader-simulation:
        condition: service_completed_successfully
#      simulation2:
#        condition: service_completed_successfully
#      simulation3:
#        condition: service_completed_successfully
    image: angelacortecchia/${PROJECT_NAME:-unknown}-charts:${VERSION:-latest}
    build:
      dockerfile: ./docker/charts/Dockerfile
      context: .
    volumes:
      - ./data:/experiment/data
      - ./charts:/experiment/charts

  finish:
    depends_on:
      charts:
        condition: service_completed_successfully
      prepare:
        condition: service_completed_successfully
    image: alpine:3.21.0
    volumes:
      - .:/experiment:rw
    entrypoint: /bin/sh -c
    command:
      - |
        find /experiment/data -type d -exec chmod 777 {} \;
        find /experiment/charts -type d -exec chmod 777 {} \;
        find /experiment/data -type f -exec chmod 666 {} \;
        find /experiment/charts -type f -exec chmod 666 {} \;