services:
  classic-vmc-batch:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/data
    environment:
      - GRADLE_TASK=runClassicVMCBatch
      - GRADLE_TASK=runFixedLeaderOptimizer

  fixed-leader-optimizer:
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/data
    depends_on:
      - classic-vmc-batch
    environment:
      - GRADLE_TASK=runFixedLeaderOptimizer

volumes:
  angela.cortecchia-volume:
    external: true