services:
  prepare:
    image: alpine:3.21.0
    volumes:
      - .:/experiment:rw
    entrypoint: /bin/sh -c
    command:
      - |
        mkdir -p /experiment/data
        chmod 777 /experiment/data
        mkdir -p /experiment/charts
        chmod 777 /experiment/charts

  fieldVMC-fixed-leader-simulation:
    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderFieldVMC/Dockerfile
    environment:
      LEADER_RADIUS: 100.0
      MAX_CHILDREN: 3
      MAX_RESOURCE: 1000.0
      MIN_SPAWN_WAIT: 40.0
      RESOURCE_LOWER_BOUND: 1.0
    depends_on:
      - prepare
    volumes:
      - ./data:/experiment/data
      
  classic-vmc-simulation:
    image: angelacortecchia/${PROJECT_NAME:-unknown}-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/classicVMC/Dockerfile
    environment:
      CLONING_RANGE: 5
      MAX_CHILDREN: 3
      MAX_RESOURCE: 3.0
      MAX_SUCCESS: 500.0
      MIN_SPAWN_WAIT: 21
      RESOURCE_LOWER_BOUND: 5.0
    depends_on:
      - prepare
    volumes:
      - ./data:/experiment/data

#  charts:
#    depends_on:
#      prepare:
#        condition: service_completed_successfully
#      classic-vmc-simulation:
#        condition: service_completed_successfully
#    image: angelacortecchia/${PROJECT_NAME:-unknown}-charts:${VERSION:-latest}
#    build:
#      dockerfile: ./docker/charts/Dockerfile
#      context: .
#    volumes:
#      - ./data:/experiment/data
#      - ./charts:/experiment/charts

  finish:
    depends_on:
      charts:
        condition: service_completed_successfully
      prepare:
        condition: service_completed_successfully
    image: alpine:3.21.0
    volumes:
      - .:/experiment:rw
    entrypoint: /bin/sh -c
    command:
      - |
        find /experiment/data -type d -exec chmod 777 {} \;
        find /experiment/charts -type d -exec chmod 777 {} \;
        find /experiment/data -type f -exec chmod 666 {} \;
        find /experiment/charts -type f -exec chmod 666 {} \;