services:
#  fixed-leader-optimizer:
#    deploy:
#      placement:
#        constraints:
#          - node.hostname==andromeda.apice.unibo.it
#    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
#    build:
#      context: .
#      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
#    volumes:
#      - angela.cortecchia-volume:/experiment/data
#    environment:
#      - MAX_SEED=500
#      - GRADLE_TASK=runFixedLeaderOptimizer
  cutting-classic-vmc-batch:
    deploy:
      placement:
        constraints:
          - node.hostname==andromeda.apice.unibo.it
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runCuttingClassicVMCBatch

  cutting-field-vmc-batch:
    deploy:
      placement:
        constraints:
          - node.hostname==andromeda.apice.unibo.it
    image: angelacortecchia/field-vmc-simulation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=500
      - GRADLE_TASK=runCuttingFixedLeaderBatch

volumes:
  angela.cortecchia-volume:
    external: true