services:
  optimizing-simulations:
    image: angelacortecchia/field-vmc-simulation
    build:
      context: .
      dockerfile: ./docker/fixedLeaderOptimizer/Dockerfile
    volumes:
      - angela.cortecchia-volume:/data
    environment:
      - GRADLE_TASK=runClassicVMCBatch
      - GRADLE_TASK=runFixedLeaderOptimizer

volumes:
  angela.cortecchia-volume:
    external: true